### ISSUE TITLE
Attacking collision

### ISSUE THREAD

**Issue by mengluwang121** [WindyDarian/DragonHunt#3]
The collision between fireball and soldier should be adjusted.

**Comment by WindyDarian** [comment]
It is done!

**Comment by WindyDarian** [comment]
So the problem was, I checked if the direct hit object is BPI_Damagable then decided whether to continue the function when a BP_FireBall lands...... But it should be an area damage. So when the fireball hits ground it couldn't damage soldiers.
But it is fixed now!!!
